# frozen_string_literal: true

default_platform :ios

platform :ios do
  ######################
  # Pre-defined values #
  ######################

  # The output folder for test coverage data
  test_output_folder = 'test_output'

  # The root fastlane folder
  fastlane_folder = 'fastlane'

  # The build scheme to use when building this framework.
  framework_scheme = 'SpotHeroEmailValidatorDemo'

  # The path to the .xcworkspace file
  workspace_file = 'SpotHeroEmailValidator.xcworkspace'

  ###########
  ## SETUP ##
  ###########

  before_all do
    use_xcode_11
  end

  def use_xcode_11
    # Select the new hotness version of Xcode.
    xcversion(version: '~> 11')
  end

  def bitrise?
    ENV.key?('BITRISE_IO')
  end

  #############################
  ## TESTING & CODE COVERAGE ##
  #############################

  desc 'Runs all tests for the framework and runs Danger if on CI.'
  lane :test do |options|
    # Set the output_directory
    output_directory = if bitrise?
                         ENV['BITRISE_DEPLOY_DIR']
                       else
                         File.join(fastlane_folder, test_output_folder)
                       end

    # Build and run the given tests
    scan(
      clean: true,
      code_coverage: true,
      devices: ['iPhone 8'],
      fail_build: true, # make false when danger is enabled
      output_directory: output_directory,
      output_types: 'html,junit',
      output_files: 'test_report.html,test_report.junit',
      scheme: framework_scheme,
      skip_build: true, # the test action will already kick off a build, don't build twice
      skip_detect_devices: true,
      skip_slack: !is_ci, # only let us know if we're on CI
      workspace: workspace_file,
    )
  end

  ######################
  ## SUCCESS HANDLING ##
  ######################

  # This gets called if the executed lanes were all successful
  after_all do |_lane|
    slack(message: 'SpotHeroEmailValidator build succeeded!', success: true) if is_ci
  end

  ######################
  ## FAILURE HANDLING ##
  ######################

  # This gets called if anything failed along the way
  error do |_lane, exception|
    slack(message: "SpotHeroEmailValidator build failed! Exception: #{exception}", success: false) if is_ci
  end
end
